apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    editable: false

  - name: Tempo
    type: tempo
    url: http://tempo:8080
    access: proxy
    editable: false

  - name: Loki
    type: loki
    url: http://loki:12345
    access: proxy
    editable: false